name: C/C++ CI

on: [push]

jobs:
  ci-linux:
    name: ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        MH_STUFF_COMPILE_LIBRARY: [true, false]
        compiler: [clang++-11, clang++-10, clang++-9, g++-9, clang++-8, g++-8, clang++-7]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add repos
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main" | sudo tee /etc/apt/sources.list.d/llvm.list
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list

    - name: Install compiler
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt clean
        sudo apt update
        sudo apt install ${{ matrix.compiler }} libc++-10-dev libc++abi-10-dev ninja-build -y

    # - name: Run tests
    #   working-directory: ./test
    #   run: make -j`grep -c ^processor /proc/cpuinfo` ${{ matrix.compiler }}_test_output.txt

    - name: Run tests
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake -DMH_STUFF_COMPILE_LIBRARY=${{ matrix.MH_STUFF_COMPILE_LIBRARY }} ../ -G Ninja
        cmake --build .
        ctest --output-on-failure
