name: C/C++ CI

on: [push]

jobs:
  ci:
    name: ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [clang++-10, clang++-9, g++-9, clang++-8, g++-8, clang++-7]

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Add repos
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main" | sudo tee /etc/apt/sources.list.d/llvm.list
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list

    - name: Install compiler
      run: |
        sudo apt update
        sudo apt install ${{ matrix.compiler }} libc++-10-dev libc++abi-10-dev -y

    - name: make runtests
      working-directory: ./test
      env:
        CXX: ${{ matrix.compiler }}
      run: make runtests
